### ISSUE TITLE
Documentation about callback functions

### ISSUE THREAD

**Issue by tuncbkose** [JuliaNLSolvers/Optim.jl#1111]
As far as I can tell, a callback function given to `optimize` is supposed to return a boolean controlling whether the optimization is supposed to stop or not. Returning `nothing` leads to an error about using a non-boolean in a boolean context. Is this documented somewhere? All I could find was the [Configurable options](https://julianlsolvers.github.io/Optim.jl/stable/user/config/#Configurable-options) page saying returning `true` stops `optimize`, which seems incomplete to me.

I can happily make a PR if I indeed didn't miss anything to expand the documentation a bit.

**Comment by pkofod** [comment]
I'm not sure if this is properly documented, no. I would be happy to review if you make a PR :) But yes, you've understood it correctly, if should return true or false and true means to stop. The whole callback design could be better because you also have poor control over what is copied / included in the state. I'm also open for discussions on changing these, but a breaking change would require a major release.

**Comment by tuncbkose** [comment]
I ran into this in trying to inspect the internal state (when I was confused about #1112), so just doing
```julia
opt = Optim.Options(..., callback=x->print(x))
optimize(..., opt)
```
lead to the non-boolean error. I think this is an innocent-enough mistake others may encounter too, so it is worth mentioning in the docs, so I'll make a PR.

I cannot comment on the general callback design since my use of Optim is very limited so far.
