### ISSUE TITLE
switch argument order for gradient and hessian evaluations?

### ISSUE THREAD

**Issue by ahwillia** [JuliaNLSolvers/Optim.jl#156]
It would be nice if the inputs `g!`, `fg!`, `h!`, etc. matched what [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl) returns when you call `gradient`, `hessian`, etc. Specifically, the storage/output vector is the first argument in ForwardDiff. 

``` julia
g! = ForwardDiff.gradient(f, mutates=true)
# compute gradient at x
g!(storage, x)
```

Meanwhile Optim expects:

``` julia
g!(x, storage)
```

I think having the mutated argument come first makes sense as a convention. However, this is a small detail, and it will break a lot of code. So maybe it is best to keep things the way they are, but wanted to bring up this possibility.

**Comment by KristofferC** [comment]
+1 from me. 

As it is right now you need to do quite some juggling with function argument to make it work with ForwardDiff, see for example https://github.com/EconForge/NLsolve.jl/blob/master/src/autodiff.jl

The problem is that many of the julia optimization/solver packages are consistent on having the mutated input last, i.e.:

https://github.com/JuliaOpt/NLopt.jl and https://github.com/EconForge/NLsolve.jl. 

so maybe it is a too disruptive of a change...

**Comment by johnmyleswhite** [comment]
I'm happy to do this after we make some other breaking changes. I've always wanted to move away from the current API.

**Comment by pkofod** [comment]
+1 for having the mutated object first. I think this is what most Julia packages/bases uses as well (push!, plot!, ...)
