### ISSUE TITLE
GSOC/JSOC proposal

### ISSUE THREAD

**Issue by mlubin** [JuliaNLSolvers/Optim.jl#169]
Any interest in putting together a proposal for [google summer of code](http://julialang.org/soc/ideas-page)?

@timholy

**Comment by pkofod** [comment]
Good idea! Will think about it.

**Comment by timholy** [comment]
I assume you flagged me because you think it would make a good project would to finish & merge work on constrained optimization? I think so too. I'll add that suggestion to the projects page.

What do you think of the CUTEst wrapper idea? My guess is that one would want to write a SIF->JuMP translator. Given the trouble I've had compiling the [existing wrapper](https://github.com/lpoo/CUTEst.jl), I suspect a native solution would be helpful.

To me, a comprehensive test suite is basically a must if we want to get serious about making Optim a world-class optimization suite.

**Comment by multidis** [comment]
+1 for constrained branch merge and a comprehensive test suite

**Comment by WenjieZ** [comment]
Hello, I would like to apply for GSoC/JSoC as a student.

First please allow me to introduce myself. I am a PhD student in machine learning, with a background in mathematics and statistics. I started to program in Julia language one year ago, which is the fifth language I have extensively used in my work (the first four are Pascal, C++, Matlab, R). Although I am still not an expert of this language, I have both a macro and a micro idea about it.

I would like to help the Julia _constrained  optimization_ functionality. However, in contrast to @timholy, I am more interested in implementing modern algorithms, such as [Frank-Wolfe](https://en.wikipedia.org/wiki/Frank%E2%80%93Wolfe_algorithm). This algorithm itself is quite old, but there is renewed interest since [this article](http://jmlr.org/proceedings/papers/v28/jaggi13).

The main attractiveness of this algorithm is that it embeds the _sparsity_ into the solution searching process, and is optimal among all solutions with the same sparsity. This is achieved by profiting from the property of _atomic norm_ (the constraint). Famous atomic norms include but not restrict to L1, nuclear norm. The former is the key of _Lasso_, while the latter is the key of _matrix approximation_. Therefore, this algorithm is rather generic and widely applicable. 

There exist currently some code in Matlab, Python and C++ on GitHub. But they work on a narrow scope of problems such as Lasso and SVM, and are not ready for deployment. It will be nice if we can realize a fast, generic Julia implementation. It will benefit both the academy and the industry, and probably bring a lot of citations.

I would like to find some mentor(s), who could help me on the Julia side, so that my implementation could be efficient and easily integrated into the JuliaOpt ecosystem.

**Comment by mlubin** [comment]
@WenjieZ, seems like an interesting project. I'm not available to mentor myself, but could you explain in what cases this Frank-Wolfe algorithm would be superior to using existing tools like Ipopt?

**Comment by timholy** [comment]
Presumably it's most attractive in cases where the objective function is only practical to compute when the parameter vector is sparse (@WenjieZ will correct me if I'm wrong).

Sounds like a fine GSoC project. The two caveats I'd raise are (1) it's a bit more specialized than what you might call "old fashioned" algorithms (because convergence is sublinear, on many problems it will be out competed by e.g. interior-point methods); (2) it sounds like there might possibly still be some research left to do on the mathematical side, and one wonders whether it might be better aligned with a masters or PhD thesis than something like GSoC (which is more about implementation). Those caveats don't negate my enthusiasm for your proposal (I think it would be really cool), but you might consider addressing both points in your application.

**Comment by WenjieZ** [comment]
Sorry for my late response.

> Presumably it's most attractive in cases where the objective function is only practical to compute when the parameter vector is sparse

I would prefer to say that we are only interested in sparse solutions. This is a phenomenon that happens in a lot of domains. For regression, we may have a data matrix whose dimension of parameter `p` is much larger that the number of records `n`. For matrix approximation, we regard that the true matrix is actually a low-rank one. In non-parametric statistics, one cannot proceed if we are not looking for a sparse solution. More and more people realize that the sparsity is the truth of the world.

This sparsity can take different forms. By using L1 norm, we are looking for a vector with few non-zero coefficients. By using L∞ norm, we are looking for a vector of only `+1/-1`. By nuclear norm (the sum of all singular values), we are looking for a low-rank matrix, etc.. Frank-Wolfe provides a generic framework to solve these problems when equipped with different norms (see Table 1 in the cited article above).

With the regards to the interior point method, I am not expert of it. I spent some time to check it. I find that it may have 2 disadvantages. It is most used in $R^n$ space, and SDP. And it needs an appropriate self-concordant barrier function. This may not be possible in an arbitrary metric space. For example, it is not suitable for this problem: $ \min\_X ||X-Y||  s.t. ||X||<r $, where the former norm is Frobenius norm, and the latter nuclear norm. If we regard the matrix as a $R^(m*n)$ vector space, it will be a high dimensional problem, where the interior point won't be efficient.

The other disadvantage is that Ipopt arrives at a sparse solution only at the end of iterations (in Lasso for instance), while for FW, the solution in each iteration is sparse, thus allows an early stop, once one is satisfied with the current solution and/or gets tired of waiting.

With regards to the caveat 2, actually this has been the subject of a [PhD thesis](http://m8j.net/math/thesis.pdf). Although there is further research, the foundation is already laid. The only inconvenience is that the API may not be fixed, since there may be future variants/acceleration of this algorithm. In this case, I can offer to maintain this package. From another point of view, this may also be a good opportunity to interact with the academy: why should the software always be the fruit of the research instead of accelerating the research as well?

**Comment by timholy** [comment]
With regards to point 1, I agree (and always have) that there's reason for genuine interest in this algorithm. Sparse problems are indeed an important space; you've made a strong case even stronger with your arguments.

With regards to point 2, I am not worried about API design; that's a normal part of the challenge. I had the impression (based on the "not ready for use" status of such code in other languages) that the mathematics might not be quite mature enough. If you're confident it is, that's good news.

**Comment by WenjieZ** [comment]
I made a [summary](https://docs.google.com/spreadsheets/d/1TqQPx_ZU79jVk5JenpaVzDD_tS80JFJ_asRhPa5UYvI/edit?usp=sharing) of the status of this algorithm on Github. There are 12 repos in all, 5 of which are just some casual code. Only 4 of them have some minimal documentation. They are written in Matlab(2), Python(1) and C++(1) on problems of Lasso, SVM and so on. I think it would be at least safe to implement in Julia Lasso and SVM. And personally, I would also like to implement the matrix approximation since I have sufficient knowledge about it. Our implementation will include most variants of this algorithm. The final result is intended to be a strict superset of the union of the above repos.

**Comment by johnmyleswhite** [comment]
I wonder if specialized methods for solving the LASSO and SVM problems belong in a different package. Still a great project idea, but our emphasis has historically been on generic optimization algorithms. Most methods we add fit under the `optimize(f, g, h, method_name)` rubric, whereas this sounds like it's a `lasso(X, y)`, `svm(X, y)` and `matrix_approximation(X)` method.

**Comment by WenjieZ** [comment]
@johnmyleswhite I'll separate your question into 2 sub-questions:

1. Whether FW is a generic optimization algorithm?
2. Can it be fit into the Optim.jl API?

For 1), absolutely, FW and its variants are all generic frameworks (higher-order function in the language of SICP). The original FW contains three components: gradient, linear minimizer and line searcher. And for different problems, these three components will take different forms. Thus, FW matches the generic optimization theme.

For 2), I do doubt the compatibility of the API with Optim.jl. Most likely, it will be an independent package like LsqFit.jl. I have thought about the different levels of API.

* the low level `fw(f, g, lm, ls)`
* the high level `lasso_fw(X, y) = fw(b->(Xb-y)^2, b->(X^T)(Xb-y), min, ls_lasso)`
* for other packages `lasso(X, y, method = :fw) = lasso_fw(X, y)`

**Comment by johnmyleswhite** [comment]
If something was submitted, I don't think this needs to be closed.

**Comment by WenjieZ** [comment]
> If something was submitted

Yes!

**Comment by pkofod** [comment]
Sure, I just figured separate issues could be opened if projects got accepted, but works for me.

**Comment by WenjieZ** [comment]
Thanks @pkofod
