### ISSUE TITLE
Use finite differencing from FiniteDiff.jl?

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/Optim.jl#378]
Is there an advantage of moving to calculate finite differences from FiniteDiff instead of Calculus? It seems like FiniteDiff is meant to replace the Calculus implementation for this?

I can do a PR if a move to FiniteDiff is beneficial.

**Comment by pkofod** [comment]
cc @johnmyleswhite

**Comment by johnmyleswhite** [comment]
There's likely to be no functionality changes from moving to FiniteDiff. It might make some of the code easier to read given the better documented API, but I wouldn't make it a priority.

**Comment by pkofod** [comment]
> There's likely to be no functionality changes from moving to FiniteDiff. It might make some of the code easier to read given the better documented API, but I wouldn't make it a priority.

so the code is basically the same? (if we disregard API)

**Comment by johnmyleswhite** [comment]
The code is effectively rewritten from scratch to clean it up, but the functionality is almost unchanged. I think the main difference is that there's now a distinction between read-only inputs and writable buffers so that you can make code that's can safely share the current position across threads, which fixes the only substantive problem people have been reporting against Calculus.jl.

**Comment by pkofod** [comment]
Just had a look. I think we should certainly make the transition, but not before it is published/in metadata.

**Comment by pkofod** [comment]
@johnmyleswhite is there a chance FiniteDiff.jl will actually be published? If not, I'm closing this.

**Comment by johnmyleswhite** [comment]
No, I'm likely not going to have time to work on Julia again given my current workload. :(

**Comment by pkofod** [comment]
I figured! Feel free to reopen this when you either a) retire and have time for Julia again or b) convince FB to go 100% Julia ;)
