### ISSUE TITLE
optimize with autodiff accumulates calls counter

### ISSUE THREAD

**Issue by amrods** [JuliaNLSolvers/Optim.jl#443]
Repeatedly calling `optimize` on a differentiable function with `autodiff` keeps increasing the Objective Calls and Gradient Calls counters. This happens with either `autodiff = :forward` or `autodiff = :finite`.

**Comment by anriseth** [comment]
I see two options here: We can either reset the counters in *Differentiable types when we call `optimize`, or store we can number store of evaluations before the run and output the difference.

**Comment by anriseth** [comment]
Out of interest, what is the use case for calling `optimize` on the same objective multiple times - are you looking for global minima by starting with multiple initial guesses? 
As a temporary fix, would it work for you to just create a new `*Differentiable` for each `optimize`?

**Comment by pkofod** [comment]
> We can either reset the counters in *Differentiable types when we call optimize

I actually thought we already did this... hmm...

**Comment by molivo** [comment]
It was more trivial than that. I was working on a script that I kept running in blocks and noticed it. Yes, if I create a new `*Differentiable` each time, it bypasses the problem, but not that I care about the number of iterations. Another thing I noticed is that the "stable" documentation is not in line with specifying `autodiff` when defining a new `*Differentiable`. And if I may ask, why did you prefer to have `autodiff` like that and not as an option to `optimize` as before?

**Comment by pkofod** [comment]
> Another thing I noticed is that the "stable" documentation is not in line with specifying autodiff when defining a new *Differentiable.

Yes, this is because the documentation hadn't been building for a while. We recently fixed it, but because we havn't released a new version since then, "stable" is unfortunately the old version that hadn't been built since march. We should maybe just tag a patch to fix this.

> And if I may ask, why did you prefer to have autodiff like that and not as an option to optimize as before?

Well, good question. It was part of creating the new `*Differentiable` types, and it just felt natural to bundle the autodiff functionality with the creation of the type instance. But... we could reintroduce the old version, such that it will promote the current objective (function, `OnceDifferentiable` or other) to the requirement imposed by the chosen method.
