### ISSUE TITLE
Move from Calculus.jl to DiffEqDiffTools.jl

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/Optim.jl#476]
DiffEqDiffTools supports much faster finite differencing routines than Calculus. 
Ref: discussion on gitter.

**Comment by anriseth** [comment]
If I understand correctly, this will also improve the support for optimization involving complex variables and functions?

**Comment by ChrisRackauckas** [comment]
@dextorious is making it handle complex variables, which means that the differentiation will be compatible with it. So then all that needs to be done is Optim.jl itself needs to be compatible complex, and it'll work. The current issue is both due to Optim (?) and/or the differentiation tools since I know ForwardDiff.jl and Calculus.jl both don't support complex numbers.

**Comment by pkofod** [comment]
Optim supports C^N->R objectives, but is that not what you mean?

**Comment by ChrisRackauckas** [comment]
How are you getting gradients for things like LFBGS?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaNLSolvers/Optim.jl/blob/master/docs/src/algo/complex.md

>For now, only explicit gradients are supported.

This is what I mean, the current block is due to the differentiation tools. I put the (?) after Optim because I didn't know if you guys had it up to here yet.

**Comment by pkofod** [comment]
Unfortunately not no, would be awesome to have auto for it

**Comment by pkofod** [comment]
Is this https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/ff050f49d2f1cc787847d48115ea571ffedd415f/src/finitediff.jl#L7 MIT license compatible?

**Comment by dextorious** [comment]
> Is this https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/ff050f49d2f1cc787847d48115ea571ffedd415f/src/finitediff.jl#L7 MIT license compatible?

As the person who wrote that, I don't know much about US-style software licensing, but the reference is to a formula in a standard academic book, not code. Not sure why that would cause an issue.

**Comment by pkofod** [comment]
I just thought that numerical recipes was no-go :) sorry if I'm wrong

**Comment by ChrisRackauckas** [comment]
You can always work from formulas and not the code.

**Comment by pkofod** [comment]
Alright just thought the code was right next to the formula, no worries then!

**Comment by dextorious** [comment]
For what it's worth, I've never actually gone through their code, the book is just a convenient reference to lots of commonly used "received wisdom" in numerical computing. That particular expression is pretty basic common sense, I'm sure there are earlier references aplenty.

**Comment by antoine-levitt** [comment]
@ChrisRackauckas I remember discussions about the different usages of complex differentiation, and seem to recall you were mainly interested in differentiating holomorphic functions. Do you have an API that supports general differentiation of non-holomorphic functions? (which non-trivial C^n -> R functions are necessarily). Otherwise, Optim uses internally real arrays to represent complex iterates and converts to complex when calling the function, so it would probably not be hard to make finite differentiation work for complex functions (I did not try to do it in my PR because I have explicit gradients for my application, and finite differentiation is anyway much too slow - what we really need for large applications is reverse diff)

**Comment by ChrisRackauckas** [comment]
Read the chats. Basically @dextorious 's approach is to just split them into two real arrays and do that. Supposedly it's even better than the 2x cost I would've expected, so at least for now that would do well.

**Comment by ChrisRackauckas** [comment]
>what we really need for large applications is reverse diff

Depends on the application.

**Comment by antoine-levitt** [comment]
> Read the chats. Basically @dextorious 's approach is to just split them into two real arrays and do that. Supposedly it's even better than the 2x cost I would've expected, so at least for now that would do well.

Great!

(by "the chats", you mean the Optim gitter? I don't see anything there, and the DiffEq gitter is much too crowded. I don't know if gitter supports it, but it would be good in general to give precise references to discussions in gitter for people who don't follow it)

>> what we really need for large applications is reverse diff
> Depends on the application.

Really? For large systems isn't the O(n) finite differencing going to kill you compared to a hand-crafted gradient or reverse diff, both of which are O(1)? Granted, there's the reverse diff overhead, but still. (I should clarify that by "large applications" I mean "a big optimization problem", not "a small optimization problem solved lots of times")

**Comment by ChrisRackauckas** [comment]
Reverse diff is for gradients. I wasn't sure we were on Optim so I was thinking we were on NLsolve where for Jacobians reverse diff isn't always a good choice. For optimization and gradients it is more straight-forward though, I agree.

**Comment by ChrisRackauckas** [comment]
The version with complex number support, native `fg!`, abstract array handling, etc. was merged and tagged. We cover everything that Optim.jl needs now except for Hessians.

>Really? For large systems isn't the O(n) finite differencing going to kill you compared to a hand-crafted gradient or reverse diff, both of which are O(1)? Granted, there's the reverse diff overhead, but still. (I should clarify that by "large applications" I mean "a big optimization problem", not "a small optimization problem solved lots of times")

That's a silly statement. Of course it's not always the best. But you cannot always do autodifferentiation, and sometimes it's too cumbersome to write out the gradient. But what this gives is an "always works" fallback: if you can evaluate the function to get numbers out, then you can numerically differenitate it. That's why it's nice, not because of speed reasons.

But that doesn't address the issue in the first place. "large applications" wasn't well defined. Applications with a large input vector, yes reverse diff, and this captures most "large optimization problems". Applications with a very expensive cost function but small parameter vector? Forward-mode autodiff can be cheaper in these cases, and many times graph building can simply fail here. So it's not as simple as "reverse mode is always better".

**Comment by ChrisRackauckas** [comment]
>(by "the chats", you mean the Optim gitter? I don't see anything there, and the DiffEq gitter is much too crowded. I don't know if gitter supports it, but it would be good in general to give precise references to discussions in gitter for people who don't follow it)

I can link to the archives in the chats, but I think the easiest way is to talk things through and then summarize. That cuts out the noise and gets to the point, the point being that splitting to real/imaginary is less than the 2x I would've assumed so for now there's no reason to treat analytic functions differently. For autodiff where we want to optimize the hell out of it, that's probably worthwhile, but this is fine for finite diff.

**Comment by pkofod** [comment]
@dextorious how is the gradient part of diffeqdifftools coming along?

**Comment by dextorious** [comment]
Gradients should be fine, that code was merged in early November and has been in use since. If you'd like any additional convenience wrappers, just let us know.

The one outstanding issue is the Hessians, which just need me or Chris to get to actually writing them. I'm mostly away from coding during the holidays, so it probably won't happen this week. Of course, you can always just take the Jacobian of the gradient, but that's suboptimal for both accuracy and performance.

**Comment by ChrisRackauckas** [comment]
Gradients are fine but slow right now. But no slower than Calculus.jl probably (since it allocates). Hessians need an implementation.

**Comment by anriseth** [comment]
> Gradients are fine but slow right now.

Are there plans / ways to make them faster?

**Comment by ChrisRackauckas** [comment]
Yes, we need non-allocating paths.

**Comment by dextorious** [comment]
Oh, that's my bad, I thought that was solved with a pre-allocating wrapper, but looking at the code I see that we only did the Jacobian case. There shouldn't be any issues doing the same thing for gradients, I believe?

**Comment by ChrisRackauckas** [comment]
Yeah. There's no technical issue there, we just need to get it done. It will speed up the Rosenbrock tests on your benchmark quite a bit BTW (SDIRK don't use gradients which is why TRBDF2 does fine). I see that, when everything else is pre-allocated, the gradients right now are the bottleneck. But it's seemingly no worse than Calculus.jl right now, which isn't a very comforting statement 👍

**Comment by dextorious** [comment]
It should be much faster than Calculus already, it does less temporary allocations, avoids bounds checking and uses compile time dispatch where possible. Still, we should get rid of the rest of the allocations and make sure there aren't any obvious issues left. I'll get it done next week if nobody else beats me to it.
