### ISSUE TITLE
Support for scalar bounds in Multivariate optimisation methods.

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaNLSolvers/Optim.jl#531]
Hey 
I feel that supporting scalar bounds in case of Multivariate function in which all the variables share the same bounds would be a good idea and lead to a cleaner interface.

**Comment by pkofod** [comment]
As we discussed on slack this is totally possible, we just have to determine if "we" (generally speaking) think it's a good idea. It certainly wouldn't be too hard to introduce, just add a new method of optimize for Fminbox.

**Comment by mohamed82008** [comment]
And you could perhaps use an immutable which subtypes `AbstractVector` that inlines as a constant everywhere you call `getindex` on it. That way you only need a thin method wrapper over the current `optimize` in Fminbox and it will just work.

**Comment by anriseth** [comment]
Are you looking for first or second order methods? We're trying to
implement a new constrained optimization interface (within the next
month?), which initially will include a second order algorithm. It may be a
better use of developer time to support this for the new interface, if that
covers your needs?

Just so I can better understand, are you working with problems where
supplying scalar/uniform bounds instead of allocating the full arrays are
crucial for performance?

**Comment by pkofod** [comment]
> Just so I can better understand, are you working with problems where supplying scalar/uniform bounds instead of allocating the full arrays are crucial for performance?

No, I'm very certain that what is being requested is a convenience API. They just want to provide `0` and `1` as positional arguments and have it mean that all lower bounds are 0 and all upper bounds are 1. I'm not sure if this will be expected or unexpected with most users, but I sort of understand it.

**Comment by mohamed82008** [comment]
It is not unusual. For my use cases, the lower and upper bounds are shared between all variables more often than not.

**Comment by pkofod** [comment]
there you go. it should now be possible to pass in scalar bounds
