### ISSUE TITLE
lighter subset

### ISSUE THREAD

**Issue by tpapp** [JuliaNLSolvers/Optim.jl#744]
When investigating a user complaint about dependencies in DynamicHMC.jl (https://github.com/tpapp/DynamicHMC.jl/issues/91), I found that Optim.jl is pulling in quite a few packages.

I am sure all of those serve a useful purpose, but I am wondering if it is possible to split off a subset for users who just need eg a quasi-Newton or trust region solver?

**Comment by pkofod** [comment]
Any specific dependencies that gave problems?

**Comment by pkofod** [comment]
I know that is not answering your questions of course. It might be possible, and if it helps avoid duplicate implementations existing then sure. However, I am not sure that many dependencies exist only for the purpose of one solver. What solver in specific are you interested in?

**Comment by tpapp** [comment]
It is not a specific dependency. I have looked at the source and I understand that what I am asking about may not be simple, and that no dependency is there without good reason.

Also, I would just need a robust and unconstrained first-order method (I have derivatives).

**Comment by pkofod** [comment]
Let me be explicit: I understand your problem. The lighter your dependencies are on dependencies, the better...

So just to take a look
```
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
DiffEqDiffTools = "01453d9d-ee7c-5054-8395-0335cb756afa"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
```

So which ones do I want to drop here? I'd love to drop Calculus, NaNMath, and maybe Parameters. Maybe also PositiveFactorizations, but probably not... So what's left? Nothing really dangerous imo. DiffEqDiffTools is guaranteed to be actively maintained I'd say. FillArrays is innocent imo. ForwardDiff should be safe. LineSearches is our own. LinearAlgebra -> stdlib. NLSolversBase is our own. Printf is stdlib. Random is stdlib. StatsBase is basically guaranteed to work. SparseArrays is stdlib, but I think we could get rid of that tbh.

**Comment by tpapp** [comment]
The original complaint is about an extra 2s of load time because of Optim, not long term support or maintenance.

Personally I don't think this is a big deal, but I would be curious what the largest contributors are to load times are (when the package is already precompiled).

**Comment by pkofod** [comment]
> The original complaint is about an extra 2s of load time because of Optim, not long term support or maintenance.

Oh okay, sorry, that was not clear to me. It would be nice if we could somehow inspect which dependencies took how long to load as part of loading the parent package.

**Comment by pkofod** [comment]
So I was actually wondering. What if there was a `Base` and then a `GradientDescent`, `BFGS`, ... package, and then an `Optim` package reexporting all of those. I'm wondering if this would actually reduce load-times for `BFGS.jl`? Probably. The only problem would be, that I would be taking some quite significant in the general registry...

**Comment by tpapp** [comment]
I experimented with load times a bit, and no matter which dependency I load it is always between 0.8s and 1.5s, so I guess a simple additive concept of load times is not the right model.

I would suggest that this is not pursued at the moment but revisited when we have more commonly established tools to benchmark and investigate load times, probably post-1.4.

**Comment by chriselrod** [comment]
Speaking of Julia 1.4 and load times, starting in 1.4 (current master) there is a generalized dot product
https://github.com/JuliaLang/julia/commit/2425ae760fb5151c5c7dd0554e87c5fc9e24de73
which causes warnings about incremental compilation being broken when loading Optim due to the definition here:
https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/multivariate/precon.jl#L23
Assuming that you'll want to use the stdlib definition starting in 1.4, mind surrounding Optim's with an `@static` version check? Obviously Julia 1.4 is many months away, so this isn't urgent by any means.

**Comment by pkofod** [comment]
>  Assuming that you'll want to use the stdlib definition starting in 1.4, mind surrounding Optim's with an `@static` version check? Obviously Julia 1.4 is many months away, so this isn't urgent by any means.

I'm aware, and yes that is the solution :)

**Comment by tpapp** [comment]
After studying the code a bit I would suggest the following:

1. Define a barebone, minimal-dependency library that defines a single *interface* for functions that Optim likes to deal with (only values, values and gradients, that and Hessians, how to access them). This should not contain an *implementation* (ie "get the above via this and that AD framework"). I am thinking of something not unlike [this part of LogDensityProblems](https://github.com/tpapp/LogDensityProblems.jl/blob/d7a3e8e82f6090efca84668764e767e10a463c2f/src/LogDensityProblems.jl#L24-L125). My understanding is that NLSolversBase was meant to be this, but now it pulls in a lot of stuff that belongs in the *implementation* below (eg ForwardDiff).

2. A separate package (or a set of packages) that transform user-provided real-valued functions to objects of the above interface with various derivatives, eg via AD or FD. This (or ideally, separate packages) would pull in DiffEqDiffTools and ForwardDiff. But the user should be free to provide derivatives manually too, with just using the above package, not this one.

3. Move methods with "special needs" (extra dependencies just for one method, eg Newton with PositiveFactorizations) into their own mini-package, depending on 1. Move methods that share machinery to their own package too (eg all methods that update a Hessian approximation).

4. Optim.jl remains the re-exporting umbrella package for usage of the above building blocks is encouraged.

Eg if I just want trust region, and can supply my own derivatives, I would just import 1. (to be able to hook into the API), and the mini-package that does trust region.

Please note that in making this suggestion, I may have overlooked some detail that comes from incomplete understanding of all the involved packages, but I think the general direction should be clear.

(Incidentally, is the mutating interface something that is justified for current Julia? For small problems, one can use static arrays, and for large ones the allocation cost is relatively negligible.)

**Comment by pkofod** [comment]
>     1. Define a barebone, minimal-dependency library that defines a single _interface_ for functions that Optim likes to deal with (only values, values and gradients, that and Hessians, how to access them). This should not contain an _implementation_ (ie "get the above via this and that AD framework"). I am thinking of something not unlike [this part of LogDensityProblems](https://github.com/tpapp/LogDensityProblems.jl/blob/d7a3e8e82f6090efca84668764e767e10a463c2f/src/LogDensityProblems.jl#L24-L125). My understanding is that NLSolversBase was meant to be this, but now it pulls in a lot of stuff that belongs in the _implementation_ below (eg ForwardDiff).

I don't think we're too far from each other, but I don't intend to split out everything into micropackages right now (not sure if at all, but not right now at least). See below, but notice that NLSolvers does not import any AD packages, and `NonDiffed`, `OnceDiffed`, `TwiceDiffed` are extremely thin wrappers. They just define how I call the objective internally and if the function type should be inferred or not. See https://github.com/pkofod/NLSolvers.jl/blob/master/src/objectives.jl and compare it to NLSolversBase (or don't look at the latter, it might make you 😭) 

>     2\. A separate package (or a set of packages) that transform user-provided real-valued functions to objects of the above interface with various derivatives, eg via AD or FD. This (or ideally, separate packages) would pull in DiffEqDiffTools and ForwardDiff. But the user should be free to provide derivatives manually too, with just using the above package, not this one.

You are correct that NLSolversBase went in the wrong direction, and NLSolvers will not depend on any AD packages for example. The ability to construct a `OnceDiffed` not a `NonDiffed` will not live in NLSolvers. As you might have noticed above, I explicity ask for the type of the objective in the `minimize!` call, but all that does is that it defines an easy way to evalute `f(x)`, `fg(x)` or `fgh(x)`. NLSolvers expects the user to do this work *OR* load the helper package `NLSolversAD` (name is not decided, but this just illustrates the point). If people want `NLSolversAD`, I assume that they are willing to load all the AD packages we support, but `NLSolvers` will not load any of them.


>     3\. Move methods with "special needs" (extra dependencies just for one method, eg Newton with PositiveFactorizations) into their own mini-package, depending on 1. Move methods that share machinery to their own package too (eg all methods that update a Hessian approximation).

I think much of this can be handled by allowing people to supply a linear solver and a trust region solver for example (or a line search step finder). I don't have PositiveFactorizations in NLSolvers for example. One reason for this is also that I default to a trust region solver if you just specify Newton, because Newton with line search is just annoying >_<


>     4\. Optim.jl remains the re-exporting umbrella package for usage of the above building blocks is encouraged.

This will be the plan, yes. I'm not going to deprecate Optim.jl, I'm just going to pull in the needed functionality at some point.

> (Incidentally, is the mutating interface something that is justified for current Julia? For small problems, one can use static arrays, and for large ones the allocation cost is relatively negligible.)

I think it is in some cases, but it depends on what you mean by "mutating interface". In NLSolvers the mutating interface is a promise to me, the library writer, that I'm allowed to say do `mul!` on the types of arrays you supply. However, the interface you see is mirrored by a nonmutating interface. Also, I require that you return the gradient if it's calculated, so you don't actually have to update the gradient array in-place (maybe this will become clearer with examples).

**Comment by pkofod** [comment]
(btw `infer` is not required here for the nonmutating interface to work, but it is required if you want 0 allocation static optimization)

**Comment by pkofod** [comment]
Please reopen if it's a problem after NLSolvers.jl is finished.
